# Oh My Zsh
ZSH=$HOME/.oh-my-zsh
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Alias
alias editzshrc='subl ~/.zshrc'
alias sourcezshrc='source ~/.zshrc'
alias ll='ls -alh'

# Exports
export EDITOR="subl --wait"
export GREP_OPTIONS='--color=auto'
export DISABLE_LS_COLORS="false"
export GOPATH=$HOME/code/go
export ZSHRC=$HOME/.zshrc
export machine="someputer"

# Path maniuplation
export PATH=$HOME/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$HOME/.cargo/bin
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"

# Set PS1 Prompt
# feeneyj on cloud-desktop in dotfiles/ at  mainline ✗
# $
export PROMPT='%{$fg_bold[red]%}$USER %{$reset_color%}%{$fg[white]%}on %{$reset_color%}%{$fg_bold[yellow]%}$machine %{$reset_color%}%{$fg[white]%}in %{$reset_color%}%{$fg_bold[blue]%}%c/ %{$reset_color%}$(git_prompt_info)
$ '
export ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[white]%}at %{$reset_color%}%{$fg_bold[blue]%}\uE0A0 %{$fg[red]%}"
export ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
export ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%} %{$fg[yellow]%}✗"
export ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%}"

# Setup language environments
## Ruby
if which rbenv > /dev/null; then
  export RBENV_ROOT=/usr/local/var/rbenv
  eval "$(rbenv init -)";
fi

## Node
if command -v nodenv 1>/dev/null 2>&1; then
  eval "$(nodenv init -)"
fi

## Python
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
  export PATH=$(python -m site --user-base)/bin:$PATH
fi

# it's a living....
if [ -f ~/.work.zshrc ]
then
  source ~/.work.zshrc
fi
