# zsh configurations
autoload -U compinit; compinit

# zsh directories
setopt auto_cd           # change into directories without cd
setopt auto_pushd        # push directory changes onto stack
setopt pushd_ignore_dups # Don’t push multiple copies of the same directory onto the directory stack.
setopt pushdminus        # Exchanges the meanings of ‘+’ and ‘-’ when used with a number to specify a directory in the stack.

# zsh completion options
zmodload -i zsh/complist # make the completion listing extenions load. Let's me define the menuselect escape binding below

setopt auto_list        # automatically list choices on ambiguous completion
setopt auto_menu        # automatically use menu completion
setopt always_to_end    # move cursor to end if word had one match
setopt auto_param_slash # If a parameter is completed whose content is the name of a directory, then add a trailing slash instead of a space.

# TODO: add awscli completion
zstyle ':completion:*' menu select       # select completions with arrow keys
zstyle ':completion:*' group-name ''     # group results by category
zstyle ':completion:*' special-dirs true # allow autocompleting of special directories
zstyle ':completion:::::' completer _expand _complete _ignored _approximate # enable approximate matches for completion

# Pressing escape will dismiss the autocomplete menu and take you back to the standard command line prompt
bindkey -M menuselect '\e' send-break

# Using https://geoff.greer.fm/lscolors/ to convert the default LSCOLORS used by Mac OS (exfxcxdxbxegedabagacad) to a format
# that zsh can understand. Tab complete will now look exactly like ls output
zstyle ':completion:*:default' list-colors 'di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43'

## zsh history
HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=10000

setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt inc_append_history     # add commands to HISTFILE in order of execution
setopt share_history          # share command history data

# According to man zshbuiltins history command is just an alias to fc -l
# history was defaulting to only the last 16 lines because it was defined as fc -l -16 -1
# this will show all history
alias history="fc -l 1"

## zsh editor
## NOTE: there is a bug in Sublime Text 4 where after saving and closing the window the terminal
##       is not brought back into focus https://github.com/sublimehq/sublime_text/issues/4460
##       For now you have to cmd+tab back to Terminal. Like a chump.
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line # press ctrl-x ctrl-e to open the current command in an editor

# Aliases
alias ll='ls -alh'
alias igrep='grep -i'

# Exports
export PATH=$HOME/bin:$PATH
export EDITOR=vim
export AWS_DEFAULT_REGION=us-west-2

# feeneyj in dotfiles/
# $ 
export PROMPT='%B%F{red}%n%f%b in %B%F{blue}%1~/%f%b
$ '

if [ "$(uname -s)" = "Darwin" ]
then
  source $HOME/.mac.zsh
fi 

if [ "$CODESPACES" = "true" ]
then
  source $HOME/.codespaces.zsh
fi

# it's a living....
if [ -f $HOME/.work.zsh ]
then
  source $HOME/.work.zsh
fi
