#!/usr/bin/env sh
set -e

export BOOTSTRAP_DEV_DIR=~/code
mkdir -p $BOOTSTRAP_DEV_DIR

export BOOTSTRAP_BIN_DIR=~/bin
mkdir -p $BOOTSTRAP_BIN_DIR

# Get directory of this script
export BOOTSTRAP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export BOOTSTRAP_SCRIPT_DIR=$BOOTSTRAP_DIR/script

if [ -x "$(command -v brew)" ]
then
  echo "brew is already installed"
else
  echo "brew is not installed. Installing..."

  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

./script/install-dotfiles
./script/install-fonts
./script/install-language-runtimes
./script/install-tools
./script/install-personal-binaries
