#!/usr/bin/env sh


if [ -x "$(command -v pip)" ]
then
  echo "upgrading pip"
  pip install --upgrade pip
else
  echo "installing pip"
  easy_install pip
fi


echo "installing / upgrading the AWS CLI"
pip install awscli --upgrade --user