#! /usr/bin/env sh

# TODO: all of these dependencies should be specified in the Dockerfile

## apt-get
# echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
# sudo apt update
# sudo apt-get install -y \
#     jq \
#     goreleaser \
#     hugo

# ## AWS
# curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
# unzip awscliv2.zip
# sudo ./aws/install
