#!/usr/bin/env sh
set -e

echo "installing dotfiles"

# TODO: this does not work on Mac
SCRIPT=$(readlink -f "$0")
THIS_DIR=$(dirname "$SCRIPT")
DIR=$THIS_DIR/..

echo "replacing existing dotfiles..."
for f in `ls -p $DIR/dotfiles | grep -v /`
do
  src=$DIR/dotfiles/$f
  dest=$HOME/.$f

  if [ -f $dest ]; then
    mv $dest $dest.old
  fi

  cp $src $dest
done

## Git
echo "configuring gitignore global"
git config --global core.excludesfile ~/.gitignore_global
