#!/usr/bin/env sh
set -e

## Dotfiles
echo "installing dotfiles"

DOTFILES_DIR="""$(dirname $0)/../script"""
for f in `ls -p $DOTFILES_DIR | grep -v /`
do
  src=$DOTFILES_DIR/$f
  dest=$HOME/.$f

  if [ -f $dest ]; then
    mv $dest $dest.old
  fi

  cp $src $dest
done

## Git
echo "configuring gitignore global"
git config --global core.excludesfile ~/.gitignore_global
