#!/usr/bin/env sh
set -e

echo "installing fonts"

BOOTSTRAP_DEV_DIR=~/code
BOOTSTRAP_MAC_FONTS_DIR=~/Library/Fonts
BOOTSTRAP_GIT_FONTS_DIR=$BOOTSTRAP_DEV_DIR/fonts

if [ -d "$BOOTSTRAP_GIT_FONTS_DIR/Menlo-for-Powerline" ]
then
  echo "Menlo-for-Powerline is already installed"
else
  echo "Menlo-for-Powerline is not installed. Installing..."
  git clone https://github.com/abertsch/Menlo-for-Powerline $BOOTSTRAP_GIT_FONTS_DIR/Menlo-for-Powerline
  cp $BOOTSTRAP_GIT_FONTS_DIR/Menlo-for-Powerline/*.ttf $BOOTSTRAP_MAC_FONTS_DIR
fi

if [ -d "$BOOTSTRAP_GIT_FONTS_DIR/powerline" ]
then
  echo "SourceCodePro for Powerline font is already installed"
else
  echo "SourceCodePro for Powerline is not installed. Installing..."
  git clone https://github.com/powerline/fonts.git $BOOTSTRAP_GIT_FONTS_DIR/powerline
  cp $BOOTSTRAP_GIT_FONTS_DIR/powerline/SourceCodePro/*.otf $BOOTSTRAP_MAC_FONTS_DIR
fi
