#!/usr/bin/env sh
set -e

echo "installing personal binaries"

arch='amd64' # TODO: update to handle ARM
os=''
if [ "$(uname -s)" = "Darwin" ]
then
    os='darwin'
else
    os='linux'
fi 

mkdir -p $HOME/bin

# Fetching Go based tools
go_tools="ccat kpr liltunnel qp spt sqsdr srv sts"

for tool in $go_tools
do
    echo "installing $tool"
    download_url=$(curl --silent https://api.github.com/repos/iamatypeofwalrus/$tool/releases/latest \
        | jq --arg OS "$os" --arg ARCH "$arch" '.assets | .[] | select(.browser_download_url | contains($OS)) | select(.browser_download_url | contains($ARCH)) | .browser_download_url' \
        | sed 's/"//g')
    
    tmp_dir=/tmp/$tool
    mkdir -p $tmp_dir
    curl --silent -L -o $tmp_dir/$tool.tar.gz $download_url
    tar xf $tmp_dir/$tool.tar.gz -C $tmp_dir
    mv $tmp_dir/$tool $HOME/bin
    rm -rf $tmp_dir
done
