#!/usr/bin/env sh

echo "installing python tools"

if [ -x "$(command -v pip)" ]
then
  echo "    already installed: pip"
else
  echo "    installing: pip"
  easy_install pip
fi

# Install CLI commands
if [ -x "$(command -v aws)" ]
then
  echo "    already installed: awscli"
else
  echo "    installing: awscli"
  pip install awscli --user
fi

if [ -x "$(command -v in2csv)" ]
then
  echo "already installed: csvkit"
else
  echo "    installing: csvkit"
  pip install csvkit
fi

# install libraries
function pip_install_library () {
  python -c "import $1"
  if [[ condition ]]
  then
    echo "    already installed: $1"
  else
    echo "    installing: $1"
    pip install $1
  fi
}

pip_install_library "pytimeparse"