#!/usr/bin/env sh
echo "installing tools"

if [ -x "$(command -v brew)" ]
then
  echo "brew is already installed"
else
  echo "brew is not installed. Installing..."

  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

## Ruby
if [ -x "$(command -v rbenv)" ]
then
  echo "rbenv is already installed"
else
  echo "rbenv is not installed. Installing..."
  brew install rbenv
fi

## Python
if [ -x "$(command -v pyenv)" ]
then
  echo "pyenv is already installed"
else
  echo "pyenv is not installed. Installing..."
  brew install pyenv
fi

eval "$(pyenv init -)"
export PATH="~/.pyenv/bin:$PATH"
export PATH=$(python -m site --user-base)/bin:$PATH

PYTHON_TWO_LATEST=$(pyenv install --list | sed 's/^[[:space:]]*//' | grep "^[2]\.[0-9]\.[0-9]*$" | tail -n 1)
PYTHON_THREE_LATEST=$(pyenv install --list | sed 's/^[[:space:]]*//' | grep "^[3]\.[0-9]\.[0-9]*$" | tail -n 1)

if pyenv versions | grep $PYTHON_TWO_LATEST >> /dev/null
then
  echo "python $PYTHON_TWO_LATEST is already installed"
else
  echo "python $PYTHON_TWO_LATEST is not installed. Installing..."
  pyenv install $PYTHON_TWO_LATEST
  pyenv rehash
fi

if pyenv versions | grep $PYTHON_THREE_LATEST >> /dev/null
then
  echo "python $PYTHON_THREE_LATEST is already installed"
else
  echo "python $PYTHON_THREE_LATEST is not installed. Installing..."
  pyenv install $PYTHON_THREE_LATEST
  pyenv rehash
fi

pyenv global $PYTHON_THREE_LATEST

# Need to put pyenv on the path!
eval "$(pyenv init --path)"

if [ -x "$(command -v pip)" ]
then
  echo "pip is already installed"
else
  echo "installing pip"
  easy_install pip
fi

if [ -x "$(command -v nodenv)" ]
then
  echo "nodenv is already installed"
else
  echo "nodenv is not installed. Installing..."
  brew install nodenv
fi

if [ -x "$(command -v go)" ]
then
  echo "go is already installed"
else
  echo "go is not installed. Installing..."
  brew install go
fi

if [ -x "$(command -v rustc)" ]
then
  echo "rust is already installed"
else
  echo "rust is not installed, Installing..."
  brew install rust
fi

# Tools that require other languages / tooling
eval "$(pyenv init --path)"

if [ -x "$(command -v jq)" ]
then
  echo "jq is already installed"
else
  echo "jq is not installed. Installing..."
  brew install jq
fi

if [ -x "$(command -v aws)" ]
then
  echo "aws cli is already installed"
else
  echo "aws cli is not installed. Installing..."
  pip install awscli --user
fi

if [ -x "$(command -v in2csv)" ]
then
  echo "csv toolkit is already installed"
else
  echo "csv toolkit is not installed. Installing..."
  pip install csvkit
fi
