#!/usr/bin/env sh

echo 'installing mac tools'

if [ -x "$(command -v brew)" ]
then
  echo "    already installed: brew"
else
  echo "    installing: brew"

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

function brewinstall () {
  if [ -x "$(command -v $1)" ]
  then
    echo "    already installed: $1"
  else
    echo "    installing: $1"
    brew install $1
  fi
}

brewinstall "jq"
brewinstall "jless"
brewinstall "wget"
brewinstall "tree"
brewinstall "gh"

if [ -x "$(command -v psql)" ]
then
  echo "    already installed: libpq"
else
  echo "    installing: libpq"
  brew install libpq
fi
